config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    post "like", to: "likes#like_toggle"
  end

  root "home#index"
  
  get 'home/index'
  get 'home/gallary' => "home#gallary"
  get 'home/new' => "home#new"
  post 'home/create' => "home#create"

  get 'home/show/:id' => "home#show"

  get 'home/edit/:id' => "home#edit"
  post 'home/update/:id' => "home#update"
  
  post 'home/destroy/:id' => "home#destroy"
  
  post 'home/gallary' => "home#gallary"
  
  get 'home/calender' => "home#calender"
  
  get 'home/intro/:id' => "home#intro"
  
  get 'home/pIntro/:id' => "home#pIntro"

end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts    
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
 
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:university])
    devise_parameter_sanitizer.permit(:account_update, keys: [:university])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:capacity])
    devise_parameter_sanitizer.permit(:account_update, keys: [:capacity])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
    
  end
end

app/controllers/enters_controller.rb
class EntersController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def index
    @posts = Post.all
  end

  def new
  end
  
  def create
    @post = Post.new
    @post.date = params[:date]
    @post.title = params[:title]
    @post.content = params[:content]
    @post.user_id = current_user.id
    
    results1 = ['동국대', '덕성여대', '아주대', '성결대', '강원대', '경기대', '한국외대', '서울시립대', '국민대', '성신여대', '남서울대', '성공회대']
    results2 = ['소주', '맥주', '소맥', '막걸리', '맛있는술(ex.복소사)', '복분자주', '칵테일', '양주', '소맥']
    @result1 = results1.sample(1)
    @result2 = results2.sample(1)
    if @result2 == results2[0]
      results3 = ['곱창, 막창', '삼겹살', '회', '족발', '소고기 무한리필', '연어']
      @result3 = results3.sample(1)
      
    elsif @result2 == results2[1]
      results3 = ['치킨', '피자', '마른안주', '회', '불닭, 불족발', '치막피', '소고기 무한리필', '수제버거', '연어', '육회']
     @result3 = results3.sample(1)
     
    elsif @result2 == results2[2]
      results3 = ['치킨', '피자', '마른안주', '회', '불닭, 불족발', '치막피', '소고기 무한리필', '수제버거', '연어', '육회']
      @result3 = results3.sample(1)
      
    elsif @result2 == results2[3]
      results3 = ['파전', '삼합', '족발']
      @result3 = results3.sample(1)
      
    elsif @result2 == results2[4]
      results3 = ['연어', '육회', '수제버거']
      @result3 = results3.sample(1)
      
    elsif @result2 == results2[5]
      results3 = ['떡볶이', '파전']
      @result3 = results3.sample(1)
      
    elsif @result2 == results2[6]
      results3 = ['치즈', '감자튀김']
      @result3 = results3.sample(1)
    
    elsif @result2 == results2[7]
      results3 = ['치즈', '회']
      @result3 = results3.sample(1)
      
    else
      results3 = ['치킨', '피자', '마른안주', '회', '불닭, 불족발', '치막피', '소고기 무한리필', '수제버거', '연어', '육회']
      @result3 = results3.sample(1)
    end
    
    results4 = ['장성원', '김승래', '신민정', '황진선', '최승호']
    @result4 = results4.sample(1)
    
    results5 = ['노래방 가즈아!', '보드게임 가즈아!', '방탈출 가즈아!', '인생네컷 가즈아!', '볼링장 가즈아!', '포켓볼 가즈아!']
    @result5 = results5.sample(1)
    
    @post.result1 = @result1.first
    @post.result2 = @result2.first
    @post.result3 = @result3.first
    @post.result4 = @result4.first
    @post.result5 = @result5.first
    @post.save
    
    redirect_to "/home/show/#{@post.id}"
    
    # if @post.save
    #   redirect_to root_path
    # else
    #   redirect_to @post_path
    # end
  end

  def show
    @post = Post.find(params[:id])
    @post.view_count = @post.view_count + 1
    @post.save
    @allpost = Post.all
  end
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.user.id != current_user.id
    redirect_to "/home/calender" 
    
    else
    @post.date = params[:date]
    @post.title = params[:title]
    @post.content = params[:content]
    @post.save
    redirect_to "/home/calender"
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    if @post.user.id != current_user.id
      redirect_to "/home/calender"
      # redirect_to "/home/index"
    else
      @post.destroy
      redirect_to "/home/calender"
    end
  end
  
  def calender
    @posts = Post.all
  end
  
  def intro
    # @post = Post.find(params[:id])
    @user = current_user
  end
  
  def pIntro
    @post = Post.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
        def like_toggle
        like = Like.find_by(user_id: current_user.id,
                            post_id: params[:post_id])
        if like.nil?
            Like.create(user_id: current_user.id,
                        post_id: params[:post_id])
        else
        like.destroy
        end
     redirect_to :back
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enters_helper.rb
module EntersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/home/calender.html.erb
<!--#CRUD-->
<head>
  
  <style>
  @font-face { font-family: 'Busan'; font-style: normal; font-weight: 400; src: url('//cdn.jsdelivr.net/korean-webfonts/1/orgs/govs/busan/Busan/Busan.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/orgs/govs/busan/Busan/Busan.woff') format('woff'); } .busan * { font-family: 'Busan', sans-serif; }
  body{
    text-align:center;
    background-color:#f8f0d8;
    font-family: 'SDKukdetopokki';
  }
  .center{
    text-align:center;
  }
  .card{
    display: inline-block;
    margin: 1.5%;
    text-align: center;
    width: 18rem;
  }
  .card-header{
    font-size: 15px;
  }
  .card-header a{
    color: #4CAF50;
  }
  .card-title{
    font-size: 14px;
    padding-top: 5%;
  }
  .card-body{
    font-size: 13px;
    text-align: left;

  }
  .btn-primary{
    float: right;
    margin: 3px;
  }
  .menu_button{
    position: absolute;
    right: 1%;
    top: 3%;
    margin: 10px;
  }
  .btn-primary{
    text-align:center
    display: block;
    color: white;
    font-size: 16px;
    cursor: pointer;
    text-align: center;
    background-color: #4CAF50;
    border-style: none;
  }
  .logo_image{
    float: left;
    position: absolute;
    left:2%;
    top: 5%;
    width: 220px;
    height: 30px;
  }
  .btn:hover{
      background-color: #ddd;
      color: black;
  }
  .menu_button_1, .menu_button_2{
    padding: 10px 25px;
    top: 10px;
    text-align:center
    display: block;
    color: white;
    font-size: 16px;
    cursor: pointer;
    text-align: center;
    border-style: none;
    background-color: #4CAF50;
    border-radius: 2px;
  }
  .menu_button_1:hover{
      background-color: #ddd;
      color: black;
  }
  </style>
</head>
    <div class = "header">
      <div class = "logo">
        <a href = "/home/index"><%= image_tag "lionlogo.png", class:"logo_image"%></a>
      </div>
      <span style = "font-size: 60px; font-family: Busan">우리 지금 만나!</span>
      <div class ="menu_button">
        <a class = "menu_button_1" href="/home/new" data-method="get">약속 생성</a>
        <a class = "menu_button_2" href="/">홈으로</a>  
      </div>
    </div>
  <pre></pre>
    <center>
    <% @posts.each do |p| %>
    
    <!--onclick="location.href='/home/show/<%= p.id %>';"-->
      <div class="card" style =" cursor: pointer;">
          <h5 class="card-header"><span><a href="/home/show/<%= p.id %>"><%= p.date%>.<%= p.title%></a></span></h5>
          <div class="card-body">
            <h5 class="card-title">주동자 : <a href="/home/pIntro/<%= p.id %>"><%= p.user.name %></a></h5>
            <p class="card-text">내용 : <%= p.content %></p>
            <p class="card-join">현재참가인원: <%= p.likes.size %></p>
            <a href="/home/destroy/<%= p.id %>" data-method="post" data-confirm="정말 삭제 하시겠습니까?" class="btn btn-primary">삭제</a>
            <a href="/home/edit/<%= p.id %>" class="btn btn-primary">수정</a>
          </div>
        </div>
      
    <%end%>
    
    
    
    
    
    
    
      
  </center>
  
  
</div>

app/views/home/edit.html.erb
<html>
	<head>
		<style>
		@font-face { font-family: 'SDKukdetopokki'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SDKukdetopokki.woff') format('woff'); font-weight: normal; font-style: normal; }

		body{
			background-color: rgb(248,240,216);  
			display: flex;
	    flex-direction: column;
	    justify-content: space-around;
	    align-items: center;
		  font-family: 'SDKukdetopokki'
		}
		h1{
		    margin-left: -600px;
		}
	.logo_home{
  margin-top:0px;
  margin-left: 350px;
  position: absolute;
  width: 150px;
}
        .btn{
            margin-left: 20px;
        }
		</style>
	</head>
	<body>
	        <a href="/home/index"><%=image_tag"logo_home.png" ,class:"logo_home"%></a> 

   
</div>
		<h1><br>예쁘게 수정해줘 히히!<br><Br></h1><br>
		<a href="/home/calender">그냥 안할래</a>
    <form action="/home/update/<%= @post.id %>" method="post">
        날짜  <input type="string" name="date" style="width:300px; height:50px;" value="월 / 일 / 요일"><br><br>
        제목  <input type="string" name="title" style="width:1000px; height:50px;"><br><br>
        내용  <input type="text" name="content" style="width:1000px; height:500px;"><br><br>
        <div class="btn">
        <input type="submit" value="저장"><br><br><br>
        </div>
    </form>
	</body>
</html>

app/views/home/gallary.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
@font-face { font-family: 'Godo'; font-style: normal; font-weight: 400; src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/godo/Godo/GodoM.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/godo/Godo/GodoM.woff') format('woff'); } @font-face { font-family: 'Godo'; font-style: normal; font-weight: 700; src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/godo/Godo/GodoB.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/godo/Godo/GodoB.woff') format('woff'); } .godo * { font-family: 'Godo', sans-serif; }

* {
    box-sizing: border-box;
}

.success {
  border-color: #4CAF50;
  color: green;
}

.success:hover {
  background-color: #4CAF50;
  color: white;
}

body {
    background-color: rgb(248,240,216);
    margin: 0;
    font-family: Arial;
}

/* The grid: Four equal columns that floats next to each other */
.column {
    float: left;
    width: 25%;
    padding: 10px;
}

/* Style the images inside the grid */
.column img {
    opacity: 0.8; 
    cursor: pointer; 
}

.column img:hover {
    opacity: 1;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

/* The expanding image container */
.container {
    position: relative;
    display: none;
}

/* Expanding image text */
#imgtext {
    position: absolute;
    bottom: 15px;
    left: 15px;
    color: white;
    font-size: 20px;
}

/* Closable button inside the expanded image */
.closebtn {
    position: absolute;
    top: 10px;
    right: 15px;
    color: white;
    font-size: 35px;
    cursor: pointer;
}
.a {
    font-family: 'Godo';
    color: green;
   }
.menu_button_2{
    padding: 10px 25px;
    top: 10px;
    text-align:center
    display: block;
    color: white;
    font-size: 16px;
    cursor: pointer;
    text-align: center;
    border-style: none;
    background-color: #4CAF50;
    border-radius: 2px;
               }
.menu_button{
    position: absolute;
    right: 1%;
    top: 3%;
    margin: 10px;
            }
            
.images{
    width:100%;
    onclick : openImg(this);
}
</style>
<p><br></p>
<div class ="menu_button">
    <a class = "menu_button_2" href="/">홈으로</a>  
</div>
</head>
<body>

<div style="text-align:center">
  <h2>
      <div class = "a">갤러리
</h2>
  <p>밑에 사진을 클릭해주세요</p>
 </div>
</div>

<!-- The four columns -->
<div class="row">
  <div class="column">
    <%= image_tag "sul1.jpg" , class: "images" %>
    
  </div>
  <div class="column">
     <%= image_tag "sul2.jpg" , class: "images"%>
  </div>
  <div class="column">
      <%= image_tag "sul3.jpg" , class: "images"%>
  </div>
  <div class="column">
  <%= image_tag "sul4.jpg" , class: "images"%>
  </div>
</div>

<div class="container">
  <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>
  <img id="expandedImg" style="width:100%">
  <div id="imgtext"></div>
</div>

<script>
function myFunction(imgs) {
    var expandImg = document.getElementById("expandedImg");
    var imgText = document.getElementById("imgtext");
    expandImg.src = imgs.src;
    imgText.innerHTML = imgs.alt;
    expandImg.parentElement.style.display = "block";
}
</script>

</body>
</html>

app/views/home/index.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset lang="ko">

    <style>
        @font-face { font-family: 'YunTaemin'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/YunTaemin.woff') format('woff'); font-weight: normal; font-style: normal; } 
        @font-face { font-family: 'HSGyoulnoonkot'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/HSGyoulnoonkot.woff') format('woff'); font-weight: normal; font-style: normal; }
        @font-face { font-family: 'godoMaum'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/godoMaum.woff') format('woff'); font-weight: normal; font-style: normal; }
        @font-face { font-family: 'SDKukdetopokki'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SDKukdetopokki.woff') format('woff'); font-weight: normal; font-style: normal; }
      body{
        
        background-color: rgb(248,240,216);
        margin-right: 15%;
        min-width: 100px;
      }
      .toon{
        font-family: 'godoMaum';
        font-size: 30pt;
      }
         .nav-link{
           background-color: #f8f0d8;
            text-align:center;
           width: 400px;
           padding-top: 17px;
            padding-bottom: 17px;           
           color: black;
           font-family: 'YunTaemin';
           /*font-family: 'HSGyoulnoonkot'*/
           font-size: 60px;
         }
         .nav-link:hover{
           background-color: #edeae6;
           color: black;
         }
      .logo{
        margin-top: 100px;
        margin-left: 30px;
        position:absolute;
      }
      .logo2{
        float: right;
        height: 30px;
        width: 260px;
      }
  
      .text_bot{
        color:gray;
        position: fixed;
        margin-top: 640px;
        margin-left: 50px;
      }
      .row{
        /*margin-top:30px;*/
        display: none;
      }
      .toon{
        position: absolute;
        margin-left: 700px;
        margin-top: 50px; 
        width: 100%;
        height: 100%;
      }
      .toon1{
          position:relative;
          margin-left: 300px;
      }
  
      .toon_1{
        position:relative;
        height: 180px;
  
      }
      .toon2{
          position:relative;
          margin-left: 500px;
          margin-top: 70px;
          display: none;
      }
  
      .toon_2{
        position:relative;
        height: 180px;
  
      }
      .toon3{
          position:relative;
          margin-left: 00px;
          margin-top: -300px;
          display: none;
      }
  
      .toon_3{
        position:relative;
        height: 180px;
  
      }
      .logout{
          position:fixed;
          top: 3%;
          right: 5%;
      }

    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
      $(".logo").click(function(){
         $(".logo").animate({left: '500px'});
         $(".row").fadeIn(1000);
         $(".toon").fadeOut(000);
      });
      $(".toon1").click(function(){
         $(".toon2").fadeIn(1000);
      });
      $(".toon2").click(function(){
         $(".toon3").fadeIn(1000);
      });
    });
    </script>

    

  </head>


  <body>

       <%=image_tag"drunken-logo.png" ,class:"logo"%>
     
             <div class="text_bot">
        <p>
          Alkohol Real Rice Thief
          <!--적당한 음주는몸에 이롭습니다 좋은 코딩은 좋은 아이디어에서나오고 아이디어는 술에서나옵니다 -->
          <!--멋쟁이 사자탈을 쓴 술쟁이 사자들을 위한 곳에 오신걸 환영합니다 당신의 주량을 마음껏 펼쳐보세요-->
          <!--<br>성공회대정해인 김승래  /  동국대송중기 장성원  /  국민대승리 최승호  /  경기대아이린 황진선  /  시립대박나래 신민정 이가 만듬 6팀 짱짱 화이팅-->
        </p>
      </div>
      <div class="row">
         <div class="col-3">
           <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
          <a class="nav-link" id="v-pills-home-tab" href="/home/index">Home</a>
          <% if user_signed_in? %>
          <% else %>
            <a class="nav-link" id="v-pills-profile-tab"  href="/users/sign_in" >Login</a>
          <% end %>
          <a class="nav-link" id="v-pills-messages-tab" href="/home/calender">Schedule</a>
          <a class="nav-link" id="v-pills-settings-tab" href="/home/gallary" >Gallry</a>
          <a class="nav-link" id="v-pills-settings-tab" href="https://uni.likelion.org/users/sign_in" >Likelion</a>
         </div>
     </div>
   </div>
  <div class="toon">
     <div class="toon1">
       <%=image_tag"drunken_1.png" ,class:"toon_1"%>
          <p>딱 한잔만...?</p>
       </div>
       <div class="toon2">
         <%=image_tag"drunken_2.png" ,class:"toon_2"%>
  
           <p>히히 치한다...!</p>
      </div>
      <div class="toon3">
         <%=image_tag"drunken_3.png" ,class:"toon_3"%>
         <p>다신술안마신다...</p>
      </div>
    </div>



  </body>
</html>
    <div class = "logout">
      <a href ="/home/index"><%=image_tag"lionlogo.png" ,class:"logo2"%></a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          
          <li style = "list-style-type : none; float:right; margin-top: 5px; font-family: SDKukdetopokki"><%= current_user.name %>님 환영합니다.</li><br>
          <li style = "list-style-type : none; float:right; font-family: SDKukdetopokki; margin-left:30px;"><%= link_to '로그아웃　', destroy_user_session_path, method: 'delete' %></li>
          <li style = "list-style-type : none; float:right; font-family: SDKukdetopokki"><a href="/home/intro/<%= current_user.id %>">　프로필</a></li>
          
         <%else %>
          <!--<li><a href="/users/sign_in">아이디 만들기</a></li>-->
          <!--<li><a href="/users/sign_up">Sign up</a></li>-->
        <%end%>
        
      </ul>
    </div>  
</div>
      

     
   

app/views/home/intro.html.erb
    <head>
        <style>
            @font-face { font-family: 'SDKukdetopokki'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SDKukdetopokki.woff') format('woff'); font-weight: normal; font-style: normal; }

		body{
			background-color: rgb(248,240,216);  
			display: flex;
	    flex-direction: column;
	    justify-content: space-around;
	    align-items: center;
		  font-family: 'SDKukdetopokki'
		}
			.logo_home{
  margin-top:0px;
  margin-left: -400px;
  position: absolute;
  width: 150px;
}
.main{
    margin-top: 50px;
}

        </style>
    </head>
    <body>
          <a href="/home/index"><%=image_tag"logo_home.png" ,class:"logo_home"%></a> 
    <div class="main">
    <div class="lion">
        <img src="/123123.jpg"></img>
    </div>
    <div class="alco">
        <h1> <br><%= @user.name %> 술쟁이 사자의 정보</h1>
        <h2>닉네임 : <%= @user.nickname %></h2>
        <h2>대학교 : <%= @user.university %></h2>
        <h2>주량 : <%= @user.capacity %></h2>
    </div>
    <div class="goback">
        <a href="/home/calender">목록으로</a><br>
    </div>
    </div>
    </body>

app/views/home/show.html.erb
<head>
<style>
body{
  background-color: rgb(248,240,216);
  font-family: 'SDKukdetopokki';
}
.logo_home{
  margin-top:-20px;
  margin-left: 160px;
  position: absolute;
  width: 150px;
}
.line1{
    margin-top: 50px;
  margin-left: 160px;
  width: 80%;
  height: 20px;
}
.title{
  margin-top: 50px;
  margin-left: 500px;
}
.text{
  /* margin-left: 30px; */
  margin-top: 70px;
  display: flex;
  flex-direction: column;
  justify-content: space-around;

}
.where, .eat, .alchoal, .member, .enter,.before{
  margin-left: 200px;
  margin-right: 200px;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
}
</style>
</head>
<body>
    <a href="/home/index"><%=image_tag"logo_home.png" ,class:"logo_home"%></a> 
  <div class="title">
<p># <%= @post.id%></p>
    
    <h2>날짜 : <%= @post.date %></h2>
   <h1><%= @post.title %></h1>
   <h5><%= @post.content %></h5>
   
   <div class="edit_destroy" style ="padding-left: 70%;">
       <p>작성자: <a href="/home/intro/<%= @post.id%>" data-method="post"><%= @post.user.name %></a><br><br> </p>
   <% if current_user.id == @post.user.id %>
       <a href="/home/edit/<%= @post.id %>">수정하기</a><br>
   <% end %>
   <a href="/home/destroy/<%= @post.id %>" data-method="post" data-confirm="정말 삭제하시겠습니까?">삭제하기</a>
   <!--<a href="/">홈으로</a>--><br>
   <a href="/home/calender">목록으로</a><br>
    <%= "조회수: #{@post.view_count}" %> 
   </div>
   
 </div>
 
 <!--조회수-->
   <div class="view_count">
   
    </div>
    
 <div class="line">
     <%=image_tag"line.png" ,class:"line1"%>
 </div>
<div class="text">
    <div class="before">
        <h1>술먹기전에 이거부터!</h1>
        <h2><%= @post.result5 %></h2>
    </div>
    <div class="line">
     <%=image_tag"line.png" ,class:"line1"%>
    </div>
 <br><br><br>
  <div class="where">
    <div class="where1">
   <h1>모일 대학</h1>
   </div>
   <div class="where2">
   <h2><%= @post.result1 %></h2>
   </div>
   </div>
   <div class="alchoal">
      <div class="alchoal1">
   <h1>마실 술</h1>
   </div>
     <div class="alchoal2">
   <h2><%= @post.result2 %></h2>
   </div>
   </div>
   <div class="eat">
     <div class="eat1">
   <h1>먹을 안주</h1>
   </div>
   <div class="eat2">
   <h2><%= @post.result3 %></h2>
   </div>
   </div>
   <div class="member">
     <div class="member1">
   <h1>오늘의 필참 멤버</h1>
   </div>
   <div class="member2">
   <h2><%= @post.result4 %></h2>
   
   </div>
   </div>
   <br>
    <div class="enter" style="font-size:20px">
        <%= @post.likes.size %> 명이 참가합니다.
            <% if current_user.is_like?(@post) %>
            <%= link_to "참가하기 취소", post_like_path(@post), method: "post" %>
            <%else %>
            <%= link_to "참가하기", post_like_path(@post), method: "post" %>
            <%end%>
    </div>
   </div>
 </body>



<!-- 라이브리 시티 설치 코드 -->
<div id="lv-container" data-id="city" data-uid="MTAyMC8zNjI1OC8xMjc5Mw==">
<script type="text/javascript">
window.livereOption = {
    refer: 'drunken-lion-godseongwon.c9users.io'
};
   (function(d, s) {
       var j, e = d.getElementsByTagName(s)[0];

       if (typeof LivereTower === 'function') { return; }

       j = d.createElement(s);
       j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
       j.async = true;

       e.parentNode.insertBefore(j, e);
   })(document, 'script');
</script>
<noscript>라이브리 댓글 작성을 위해 JavaScript를 활성화 해주세요</noscript>
</div>
<!-- 시티 설치 코드 끝 -->